// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqRAYlqYFxua0ETrr1MNTf2Go9eC0-s1c',
    appId: '1:702424016930:web:4abf8a2676725f929b027b',
    messagingSenderId: '702424016930',
    projectId: 'tjessed-leo',
    authDomain: 'tjessed-leo.firebaseapp.com',
    databaseURL: 'https://tjessed-leo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tjessed-leo.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDNavd_fAmPecfXN7-fo9oB91D9OAd0bA',
    appId: '1:702424016930:android:9a80e9b725dece5f9b027b',
    messagingSenderId: '702424016930',
    projectId: 'tjessed-leo',
    databaseURL: 'https://tjessed-leo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tjessed-leo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4CyyMTUCu939jzPqONP6ceKyowl3T1fw',
    appId: '1:702424016930:ios:0f0d196573dd9b779b027b',
    messagingSenderId: '702424016930',
    projectId: 'tjessed-leo',
    databaseURL: 'https://tjessed-leo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tjessed-leo.firebasestorage.app',
    iosClientId: '702424016930-ogu8kamon0iuonord0lqj35n2416v13o.apps.googleusercontent.com',
    iosBundleId: 'com.laurensia.neo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4CyyMTUCu939jzPqONP6ceKyowl3T1fw',
    appId: '1:702424016930:ios:0f0d196573dd9b779b027b',
    messagingSenderId: '702424016930',
    projectId: 'tjessed-leo',
    databaseURL: 'https://tjessed-leo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tjessed-leo.firebasestorage.app',
    iosClientId: '702424016930-ogu8kamon0iuonord0lqj35n2416v13o.apps.googleusercontent.com',
    iosBundleId: 'com.laurensia.neo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqRAYlqYFxua0ETrr1MNTf2Go9eC0-s1c',
    appId: '1:702424016930:web:c1002b23e210e1e29b027b',
    messagingSenderId: '702424016930',
    projectId: 'tjessed-leo',
    authDomain: 'tjessed-leo.firebaseapp.com',
    databaseURL: 'https://tjessed-leo-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tjessed-leo.firebasestorage.app',
  );
}
